######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/ijb-basic.action,v $
# 
#  $Id: ijb-basic.action,v 1.3 2002/03/13 14:24:09 swa Exp $
#
#  Purpose     :  Very basic actions file, see
#                 http://ijbswa.sourceforge.net/faq/questions.html#CONFIGFILES
# 
# We value your feedback. However, to provide you with the best support,
# please note:
#  
#  * Use the support forum to get help:
#    http://sourceforge.net/tracker/?group_id=11118&atid=211118
#  * Submit bugs only thru our bug forum:
#    http://sourceforge.net/tracker/?group_id=11118&atid=111118 
#    Make sure that the bug has not already been submitted. Please try
#    to verify that it is a Junkbuster bug, and not a browser or site
#    bug first. If you are using your own custom configuration, please
#    try the stock configs to see if the problem is a configuration
#    related bug. And if not using the latest development snapshot,
#    please try the latest one. Or even better, CVS sources.
#  * Submit feature requests only thru our feature request forum:
#    http://sourceforge.net/tracker/?atid=361118&group_id=11118&func=browse
#      
# For any other issues, feel free to use the mailing lists:
# http://sourceforge.net/mail/?group_id=11118
#    
# Anyone interested in actively participating in development and related
# discussions can join the appropriate mailing list here:
# http://sourceforge.net/mail/?group_id=11118. Archives are available
# here too.
# 
######################################################################

######################################################################
# Aliases
######################################################################
{{alias}}
+imageblock = +block +image

######################################################################
# Defaults
######################################################################
{\
+deanimate-gifs{last} \
+image-blocker{trans} \
+hide-referer{forge} \
+no-cookies-keep \
-filter \
}
/ # Match all URLs


######################################################################
# Specials
######################################################################
{+image}
#############################################################################
/.*\.gif
/.*\.jpe?g
/.*\.png

#############################################################################
{+imageblock}
#############################################################################
.ad.doubleclick.net
.adforce.imgis.com
.focalink.com

######################################################################
# Blocklist:
######################################################################
{+block}
#############################################################################

# generic hosts (probably most effective)
ad*.
.*ads.
banner.

/.*/(.*[-_.])?ads?[0-9]?(/|[-_.].*|\.(gif|jpe?g))
/.*/(.*[-_.])?count(er)?(\.cgi|\.dll|\.exe|[?/])
/.*/(ng)?adclient\.cgi
/.*/(plain|live|rotate)[-_.]?ads?/
/.*/(sponsor)s?[0-9]?/
/?.*/_?(plain|live)?ads?(-banners)?/
/?.*/abanners/
/?.*/ad(sdna_image|gifs?)/
/?.*/ad(server|stream|juggler)\.(cgi|pl|dll|exe)
/?.*/adbanners/
/?.*/adserver
/?.*/adstream\.cgi
/?.*/adv((er)?ts?|ertis(ing|ements?))?/
/?.*/anzei(gen)?/?
/?.*/ban[-_]cgi/
/?.*/banner_?ads/
/?.*/banner_?anzeigen
/?.*/bannerimage/
/?.*/banners?/
/?.*/banners?\.cgi/
/?.*/cgi-bin/centralad/getimage
/?.*/images/addver\.gif
/?.*/images/advert\.gif
/?.*/images/marketing/.*\.(gif|jpe?g)
/?.*/place-ads
/?.*/popupads/
/?.*/promobar.*
/?.*/publicite/
/?.*/randomads/.*\.(gif|jpe?g)
/?.*/rekla(ma|me|am)/.*\.(gif|jpe?g)
/?.*/siteads/
/?.*/sponsor.*\.gif
/?.*/sponsors?[0-9]?/
/?.*/ucbandeimg/
/?.*/werb\..*
/?.*/werbebanner/
/?.*/werbung/.*\.(gif|jpe?g)
/?.*/adv\.   # www.telegraaf.nl
/?.*/advert[0-9]+\.jpg
/?.*bann\.gif
/?.*/ads/
/_banner/
/ad_images/
/adgenius/
/adimages/
/viewad/
/adserve/
/adverts/
/annonser?/
/bando/
/bannerad/
/bannerfarm/
/bin/getimage.cgi/...\?AD
/bin/nph-oma.count/ct/default.shtml
/bin/nph-oma.count/ix/default.html
/cgi-bin/getimage.cgi/....\?GROUP=
/cgi-bin/nph-load
/cgi-bin/webad.dll/ad
/cwmail/acc\.gif
/cwmail/amzn-bm1\.gif
/db_area/banrgifs/
/gif/teasere/
/grafikk/annonse/
/graphics/defaultAd/
/grf/annonif
/htmlad/
/image\.ng/AdType
/image\.ng/transactionID
/images/.*/.*_anim\.gif # alvin brattli
/ip_img/.*\.(gif|jpe?g)
/marketpl*/
/minibanners/
/netscapeworld/nw-ad/
/promotions/houseads/
/rotads/ 
/rotateads/
/rotations/ 
/torget/jobline/.*\.gif
/viewad/
/werbung/
/worldnet/ad\.cgi
/zhp/auktion/img/
/cgi-bin/nph-adclick.exe/
/?.*/Image/BannerAdvertising/
/?.*/ad-bin/
/?.*/adlib/server\.cgi
/?.*/gsa_bs/gsa_bs.cmdl
/autoads/
/anz/pics/
# for our finnish friends, by Kai Puolamaki <Kai.Puolamaki@iki.fi>
/?.*/mainos/*.*/.*\.gif
/?.*/mainos/*.*/.*\.jpe?g
# more from a finnish friend Petri Haapio <pha@iki.fi>
/?.*/(.*[-_.].*)?maino(kset|nta|s).*(/|\.(gif|html?|jpe?g|png))
/?.*/(ilm(oitus)?|kampanja)(hallinta|kuvat?)(/|\.(gif|html?|jpe?g|png))
# <jwz@jwz.org>
/?.*/adfinity
/?.*/[?]adserv
/?.*/bizgrphx/
/?.*/smallad2\.gif
/?.*/ana2ad\.gif
/?.*/adimg/
/?.*/.*counter\.pl
/?.*/spin_html/
/?.*/images/topics/topicgimp\.gif
.discovery.com/.*banner_id
/?.*/.*bannr\.gif
.cruel.com/images/
.idrink.com/frm_bottom.htm
/?.*/.*pb_ihtml\.gif
/?.*/ph-ad.*\.focalink\.com
/cgi-bin/adjuggler

# ms sucks !
/.*(ms)?backoff(ice)?.*\.(gif|jpe?g)
/.*(/ie4|/ie3|msie|sqlbans|powrbybo|activex|backoffice|explorer|netnow|getpoint|ntbutton|hmlink).*\.(gif|jpe?g)
/.*activex.*(gif|jpe?g)
/.*explorer?.(gif|jpe?g)
/.*freeie\.(gif|jpe?g)
/.*/ie_?(buttonlogo|static?|anim.*)?\.(gif|jpe?g)
/.*ie_sm\.(gif|jpe?g)
/.*msie(30)?\.(gif|jpe?g)
/.*msnlogo\.(gif|jpe?g)
/.*office97_ad1\.(gif|jpe?g)
/.*pbbobansm\.(gif|jpe?g)
/.*powrbybo\.(gif|jpe?g)
/.*sqlbans\.(gif|jpe?g)
/.*exc_ms\.gif
/.*ie4get_animated\.gif
/.*ie4_animated\.gif
/.*n_iemap\.gif
/.*ieget\.gif
/.*logo_msnhm_*
/.*mcsp2\.gif
/.*msn2\.gif
/.*add_active\.gif
/.*n_msnmap\.gif
/.*Ad00\.gif
/.*s_msn\.gif
/.*addchannel\.gif
/.*adddesktop\.gif
/?.*/ns4\.gif
/?.*/v3sban\.gif
/?.*/?FPCreated\.gif
/?.*/opera35\.gif
/?.*/opera13\.gif
/?.*/opera_b\.gif
/?.*/ie_horiz\.gif
/?.*/ie_logo\.gif
# ... and even more!
/?.*/favicon\.ico

/?.*/images/na/us/brand/
/?.*/advantage\.(gif|jpg)
/?.*/advanbar\.(gif|jpg)
/?.*/advanbtn\.(gif|jpg)
/?.*/biznetsmall\.(gif|jpg)
/?.*/utopiad\.(gif|jpg)
/?.*/epipo\.(gif|jpg)
/?.*/amazon([a-zA-Z0-9]+)\.(gif|jpg)
/?.*/bnlogo.(gif|jpg)
/?.*/buynow([a-zA-Z0-9]+)\.(gif|jpg)

# for the dutch folks by a dutch friend gertjan@west.nl
/?.*/Advertenties/
/?.*/Adverteerders/
.netdirect.nl/nd_servlet/___

.admaximize.com
.imgis.com

# wayne@staff.msen.com
a*.*.*.yimg.com/([0-9]*|\/)*us.yimg.com/*

####################################################
# Jon's addition:
#
# The Register ads - oh, and all images in Register stories (sigh).
www.theregister.co.uk/media/

# Used on http://www.theregister.co.uk/
# Sample advert URL:
# http://secure.webconnect.net/cgi-bin/webconnecthome.dll?F467
.webconnect.net

# Dilbert:
www.dilbert.com/comics/dilbert/images/.*_140x800.*\.gif

# stattrack.com
# Uses URL: http://www.stattrack.com/cgi-bin/stats/image.cgi
/cgi-bin/stats/
# And loads JavaScript from http://www.stattrack.com/stats/code
www.stattrack.com/stats/

#Now they're Yahoo GeoCities, their junk is in a different place.
##geo.yahoo.com/serv
##visit.geocities.com/visit.gif
.yimg.com/?.*/www.geocities.com/js_source
#http://us.toto.geo.yahoo.com/toto?s=76001086
.geo.yahoo.com
.visit.geocities.com
.yimg.com/?.*/www.geocities.com/

.exitexchange.com

#SourceForge ads.
sfads.osdn.com

#This site traps the browser
.webhideout.com

#privacy.net runs ads
.a.consumer.net

#Lindsay.Marshall@newcastle.ac.uk suggested these, to kill Opera adverts:
www.qksrv.net
mirror.qkimg.net

#js
dinoadserver*.roka.net
logout.gmx.net
logout.tvspielfilm.de
gmx.tvspielfilm.de
www.freenet.de/customerindex\.html
/?.*/phpAds
.fxweb.com/v2-trackrun\.cgi
rtldating.peopleunited.de
.advertising.com
www.zdnet.com/fcgi-bin/
service.bfast.com/bfast/serve
199.172.144.25
fourohfour.nbci.com/Members404Error.php3
.adtech.de
.adlink.de
www.fair-ist-mehr.de/cgi-bin/bt.pl
.linkexchange.
/?.*/adpage.asp
/ADS
.net-on.net
rstrip.namezero.com
62.26.220.2
.doubleclick.net
.adserver.yahoo.com

#############################################################################
{-block}
#############################################################################
.admin.
.edu
.ac.uk    # English Universities too! - Jon
.uni-*.de # What about Germany? --oes
# my banking stuff => no ads.
.comdirekt.de
.comdirect.de
.teledata.de
# Jon's addition: MSDN
.msdn.microsoft.com
# .*ads. matches prdownloads.sourceforge.net and many other download sites
# The fix is:
.*downloads.

######################################################################
# 
#  Copyright   :  Written by and Copyright (C) 2001 the SourceForge
#                 IJBSWA team.  http://ijbswa.sourceforge.net
# 
#                 Based on the Internet Junkbuster originally written
#                 by and Copyright (C) 1997 Anonymous Coders and 
#                 Junkbusters Corporation.  http://www.junkbusters.com
# 
#                 This program is free software; you can redistribute it 
#                 and/or modify it under the terms of the GNU General
#                 Public License as published by the Free Software
#                 Foundation; either version 2 of the License, or (at
#                 your option) any later version.
# 
#                 This program is distributed in the hope that it will
#                 be useful, but WITHOUT ANY WARRANTY; without even the
#                 implied warranty of MERCHANTABILITY or FITNESS FOR A
#                 PARTICULAR PURPOSE.  See the GNU General Public
#                 License for more details.
# 
#                 The GNU General Public License should be included with
#                 this file.  If not, you can view it at
#                 http://www.gnu.org/copyleft/gpl.html
#                 or write to the Free Software Foundation, Inc., 59
#                 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
######################################################################
