######################################################################
# 
#  File        :  $Source: /cvsroot/ijbswa/current/intermediate.action,v $
# 
#  $Id: intermediate.action,v 1.3 2002/03/26 22:29:54 swa Exp $
#
#  Purpose     :  More agressive actions file, see
#                 http://www.privoxy.org/faq/questions.html#CONFIGFILES
# 
#  Copyright   :  Written by and Copyright
#                 Privoxy team. http://www.privoxy.org/
#
#                 Based on the Internet Junkbuster originally written
#                 by and Copyright (C) 1997 Anonymous Coders and
#                 Junkbusters Corporation.  http://www.junkbusters.com
#
# We value your feedback. However, to provide you with the best support,
# please note:
#  
#  * Use the support forum to get help:
#    http://sourceforge.net/tracker/?group_id=11118&atid=211118
#  * Submit bugs only thru our bug forum:
#    http://sourceforge.net/tracker/?group_id=11118&atid=111118 
#    Make sure that the bug has not already been submitted. Please try
#    to verify that it is a Junkbuster bug, and not a browser or site
#    bug first. If you are using your own custom configuration, please
#    try the stock configs to see if the problem is a configuration
#    related bug. And if not using the latest development snapshot,
#    please try the latest one. Or even better, CVS sources.
#  * Submit feature requests only thru our feature request forum:
#    http://sourceforge.net/tracker/?atid=361118&group_id=11118&func=browse
#      
# For any other issues, feel free to use the mailing lists:
# http://sourceforge.net/mail/?group_id=11118
#    
# Anyone interested in actively participating in development and related
# discussions can join the appropriate mailing list here:
# http://sourceforge.net/mail/?group_id=11118. Archives are available
# here too.
# 
######################################################################

######################################################################
# Aliases
######################################################################

######################################################################
# Defaults
######################################################################

######################################################################
# Specials
######################################################################

######################################################################
# Imagelist:
######################################################################

######################################################################
# Blocklist:
######################################################################

######################################################################
# 
#  Copyright   :  Written by and Copyright (C) 2001 the SourceForge
#                 Privoxy team. http://www.privoxy.org/
# 
#                 Based on the Internet Junkbuster originally written
#                 by and Copyright (C) 1997 Anonymous Coders and 
#                 Junkbusters Corporation.  http://www.junkbusters.com
# 
#                 This program is free software; you can redistribute it 
#                 and/or modify it under the terms of the GNU General
#                 Public License as published by the Free Software
#                 Foundation; either version 2 of the License, or (at
#                 your option) any later version.
# 
#                 This program is distributed in the hope that it will
#                 be useful, but WITHOUT ANY WARRANTY; without even the
#                 implied warranty of MERCHANTABILITY or FITNESS FOR A
#                 PARTICULAR PURPOSE.  See the GNU General Public
#                 License for more details.
# 
#                 The GNU General Public License should be included with
#                 this file.  If not, you can view it at
#                 http://www.gnu.org/copyleft/gpl.html
#                 or write to the Free Software Foundation, Inc., 59
#                 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
######################################################################
