.\" Revised man page 10/13/01, for development version.
.\" Hal Burgiss <hal@foobox.net> 
.\" for Junkbuster developers: ijbswa-developers@lists.sourceforge.net
.\"
.TH JUNKBUSTER 1 "v2.9.11 (beta) Date: 2002/02/24"

.SH NAME
\fBjunkbuster\fP
- The
Internet Junkbuster
Proxy
\s-2(TM)\s+2
.SH SYNOPSIS
\fBjunkbuster\fP
[--help] [--version] [--no-daemon] [--pidfile \fIpidfile\fP] 
\fI\&[config_file]\fP (Unix)
.br
\fBjunkbstr.exe\fP
\fI\&[config_file]\fP
(Windows)
.br

.SH OPTIONS
\fBJunkbuster\fP may be invoked with the following command-line options:
.TP
.BR --version " (unix only)"
Print version info and exit.
.TP
.BR --help " (unix only)"
Print a short usage info and exit.
.TP
.BR --no-daemon " (unix only)"
Don't become a daemon, i.e. don't fork and become process group
leader, don't detach from controlling tty.
.TP
\fB --pidfile\fP \fIpidfile\fP (unix only)
On startup, write the process ID to \fIpidfile\fP. Delete the
\fIpidfile\fP on exit. Failiure to create or delete the
\fIpidfile\fP is non-fatal. If no \fB--pidfile\fP option
is given, no PID file will be used.

.PP
If the \fIconfig file\fP is not specified on the command line,
\fBJunkbuster\fP will look for a file named \fBconfig\fP in the 
current directory (except on Win32 where it will try \fBconfig.txt\fP).


.SH DESCRIPTION
\fBJunkbuster\fP
is an instrumentable HTTP proxy that filters the 
\s-2HTTP\s0
data stream between
web servers and browsers.
\fBJunkbuster\fP can be used to protect privacy, manage cookies, filter web
page content, manage access restrictions, and to discard such annoying Internet
junk as ads, banners, and pop-ups. Or whatever other annoyances strike your
fancy.

.SH INSTALLATION AND USE
Browsers must be configured to use 
\fBJunkbuster\fP
(the default is localhost, 
port 8118).
To set the 
\s-2HTTP\s0
proxy in Netscape and Mozilla,
go through:
\fB\&Edit\fP;
\fB\&Preferences\fP;
\fB\&Advanced\fP;
\fB\&Proxies\fP;
\fB\&Manual Proxy Configuration\fP;
\fB\&View\fP.
.P
For Internet Explorer,
go through:
\fB\&Tools\fP;
\fB\&Internet Properties\fP;
\fB\&Connections\fP;
\fB\&LAN Settings\fP.
.P
Set the HTTP proxy location for localhost, port 8118.
The
Secure (SSL) Proxy\" ijbfaq.html#security
should also be set to the same values,
otherwise
\fB\&https:\fP
\s-2URL\s0s
won't be proxied.
.P
For other browsers, check the documentation.

.SH CONFIGURATION
All \fBJunkbuster\fP configuration is done via the various configuration 
files. The default configuration files are: \fIconfig\fP, 
\fIijb.action\fP, and \fIre_filterfile\fP. These are well commented. 
On Unix and Unix-like systems, these are located in \fI/etc/junkbuster/\fP 
by default. On Windows, OS/2 and AmigaOS, these files are in the same directory 
as the \fBJunkbuster\fP executable. 
.P
The name and number of configuration files has changed from previous versions,
and is subject to change as development progresses. In fact, the configuration
itself is changed and much more sophisticated. See the user-manual for a brief
explanation of all configuration options.
.P
\fBJunkbuster's\fP configuration parameters can be viewed at
\fIhttp://ijbswa.sourceforge.net/config\fP. This is an internal page. In
addition, the \fIijb.action\fP file can be edited here, and \fBJunkbuster\fP can
be toggled on/off.

.SH "SAMPLE CONFIGURATION"
.PP
A brief example of what an \fIijb.action\fP configuration might look like:
.PP
.nf

# Define a few useful custom aliases for later use
{{alias}}
# Don't accept cookies
+no-cookies = +no-cookies-set +no-cookies-read
# Do accept cookies
-no-cookies = -no-cookies-set -no-cookies-read
+imageblock = +block +image

## Default Policies (actions) ############################
{ \\
 -block \\
 -downgrade \\
 +fast-redirects \\
 +filter \\
 +no-compression \\
 +hide-forwarded \\
 +hide-from{block} \\
 +hide-referer{forge} \\
 -hide-user-agent \\
 -image \\
 +image-blocker{blank} \\
 +no-cookies-keep \\
 -no-cookies-read \\
 -no-cookies-set \\
 +no-popups \\
 -vanilla-wafer \\
 -wafer \\
}
/

# Now set exceptions to the above defined policies #######

# Sites where we want persistant cookies
{-no-cookies -no-cookies-keep}
 .redhat.com
 .sun.com
 .yahoo.com
 .msdn.microsoft.com

# This site requires cookies AND 'fast-redirects' on
{-no-cookies -no-cookies-keep -fast-redirects}
 .nytimes.com

# Add custom headers, and turn off filtering of page source
{+add-header{X-Privacy: Yes please} #-add-header{*} \\
 +add-header{X-User-Tracking: No thanks!} -filter}
 privacy.net

# Block, and treat these URLs as 'images'.
{+imageblock}
 .adforce.imgis.com
 .ad.preferences.com/image.*
 .ads.web.aol.com
 .ad-adex3.flycast.com
 .ad.doubleclick.net
 .ln.doubleclick.net
 .ad.de.doubleclick.net
 /.*/count\\.cgi\\?.*df=
 194.221.183.22[1-7]
 a196.g.akamai.net/7/196/2670/000[12]/images.gmx.net/i4/images/.*/

# Block any URLs that match these patterns
{+block}
 /.*/(.*[-_.])?ads?[0-9]?(/|[-_.].*|\\.(gif|jpe?g))
 /.*/(plain|live|rotate)[-_.]?ads?/
 /.*/(sponsor)s?[0-9]?/
 /.*/ad(server|stream|juggler)\\.(cgi|pl|dll|exe)
 /.*/adbanners/
 /.*/adv((er)?ts?|ertis(ing|ements?))?/
 /.*/banners?/
 /.*/popupads/
 /.*/advert[0-9]+\\.jpg
 /ad_images/
 /.*/ads/
 /images/.*/.*_anim\\.gif
 /rotations/ 
 /.*(ms)?backoff(ice)?.*\\.(gif|jpe?g)
 195.63.104.*/(inbox|log|meld|folderlu|folderru|log(in|out)[lmr]u|)
 .images.nytimes.com
 .images.yahoo.com/adv/
 /.*cnnstore\\.gif

.fi
.sp
.PP
See the comments in the configuration files themselves, or the user-manual 
for explanations of the above syntax, and other \fBJunkbuster\fP configuration 
options.

.SH "FILES"
\fI/usr/sbin/junkbuster\fP
.br
\fI/etc/junkbuster/config\fP
.br
\fI/etc/junkbuster/ijb.action\fP
.br
\fI/etc/junkbuster/ijb-advanced.action\fP
.br
\fI/etc/junkbuster/ijb-basic.action\fP
.br
\fI/etc/junkbuster/ijb-intermediate.action\fP
.br
\fI/etc/junkbuster/re_filterfile\fP
.br
\fI/etc/junkbuster/trust\fP
.br
\fI/etc/junkbuster/templates/*\fP
.br
\fI/var/log/junkbuster/logfile\fP

.P
Various other files should be included, but may vary depending on platform 
and build configuration. More documentation should be included in the local
documentation directory, though is not complete at this time.

.SH SIGNALS
\fBJunkbuster\fP teriminates on the \fBSIGINT\fP, \fBSIGTERM\fP and \fBSIGABRT\fP
signals. Log rotation scripts may cause a re-opening of the logfile by sending
a \fBSIGHUP\fP to \fBJunkbuster\fP. Note that unlike other daemons, \fBJunkbuster\fP
does not need to be made aware of config file changes by \fBSIGHUP\fP -- it will
detect them automatically.
 
.SH NOTES
This is a \fBBETA\fP version of \fBJunkbuster\fP. Not all features are  
complete.
.br
Please see the user-maual on how to contact the developers for 
feature requests, reporting problems, and other questions.

.SH BUGS
Probably. Please see the user-manual for how and where to report bugs.

.SH SEE ALSO
.br
http://ijbswa.sourceforge.net/config
.br
http://ijbswa.sourceforge.net/
.br
http://sourceforge.net/projects/ijbswa
.br
http://www.waldherr.org/junkbuster/\" waldherr.org#
.br
http://www.junkbusters.com/ht/en/cookies.html\" cookies.html#
.br
http://privacy.net/analyze/
.br
http://www.squid-cache.org/
.br
http://linuxalpha.ch/packages/

.SH DEVELOPMENT TEAM
.br
 Stefan Waldherr 
.br
 Andreas Oesterhelt 
.br
 Jon Foster 
.br
 Markus Breitenbach
.br
 Thomas Steudten
.br
 David Schmidt
.br
 Haroon Rafique
.br
 Joerg Strohmayer
.br
 Shamim Mohamed
.br
 Sarantis Paskalis
.br
 Gabriel L. Somlo
.br
 John Venvertloh
.br
 Hal Burgiss

.SH COPYRIGHT AND LICENSE
Orginally written by, and copyrighted by, the Anonymous Coders and Junkbusters
Corporation. 
.P
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.P
Internet Junkbuster
Proxy
is a
trademark\" legal.html#marks
of Junkbusters Corporation.
