#############################################################################
# Defaults
#############################################################################
{ \
+change-x-forwarded-for{block} \
+hide-from-header{block} \
+set-image-blocker{pattern} \
}
/ # Match all URLs
